export const EXPENSE_CATEGORY_IDS = [
  "food",
  "cafe_snacks",
  "groceries",
  "transport",
  "fuel",
  "taxi_cabs",
  "parking_tolls",
  "rent",
  "utilities",
  "household",
  "home_repair",
  "shopping",
  "clothing",
  "electronics",
  "subscriptions",
  "travel",
  "entertainment",
  "partying",
  "hobbies",
  "gym_fitness",
  "health",
  "personal_care",
  "education",
  "kids_family",
  "pets",
  "work",
  "gifts",
  "insurance",
  "emi_loans",
  "taxes_fees",
  "investment",
  "charity",
  "other",
];

export const INCOME_CATEGORY_IDS = [
  "salary",
  "freelance",
  "business",
  "bonus",
  "investment_return",
  "interest",
  "rental_income",
  "cashback",
  "reimbursement",
  "gift",
  "refund",
  "other",
];

export const CATEGORY_META = {
  food: { label: "Food", icon: "🍔", color: "bg-orange-100 text-orange-700" },
  cafe_snacks: { label: "Cafe & snacks", icon: "☕", color: "bg-orange-100 text-orange-700" },
  groceries: { label: "Groceries", icon: "🛒", color: "bg-lime-100 text-lime-700" },
  transport: { label: "Transport", icon: "🚗", color: "bg-blue-100 text-blue-700" },
  fuel: { label: "Fuel", icon: "⛽", color: "bg-amber-100 text-amber-700" },
  taxi_cabs: { label: "Taxi & cabs", icon: "🚕", color: "bg-yellow-100 text-yellow-700" },
  parking_tolls: { label: "Parking & tolls", icon: "🅿️", color: "bg-slate-100 text-slate-700" },
  rent: { label: "Rent", icon: "🏠", color: "bg-purple-100 text-purple-700" },
  utilities: { label: "Utilities", icon: "💡", color: "bg-yellow-100 text-yellow-700" },
  household: { label: "Household", icon: "🧹", color: "bg-stone-100 text-stone-700" },
  home_repair: { label: "Home repair", icon: "🔧", color: "bg-zinc-100 text-zinc-700" },
  shopping: { label: "Shopping", icon: "🛍️", color: "bg-pink-100 text-pink-700" },
  clothing: { label: "Clothing", icon: "👕", color: "bg-violet-100 text-violet-700" },
  electronics: { label: "Electronics", icon: "💻", color: "bg-sky-100 text-sky-700" },
  subscriptions: { label: "Subscriptions", icon: "📱", color: "bg-sky-100 text-sky-700" },
  travel: { label: "Travel", icon: "✈️", color: "bg-indigo-100 text-indigo-700" },
  partying: { label: "Partying", icon: "🎉", color: "bg-fuchsia-100 text-fuchsia-700" },
  entertainment: { label: "Entertainment", icon: "🎬", color: "bg-indigo-100 text-indigo-700" },
  hobbies: { label: "Hobbies", icon: "🎨", color: "bg-fuchsia-100 text-fuchsia-700" },
  gym_fitness: { label: "Gym & fitness", icon: "🏋️", color: "bg-teal-100 text-teal-700" },
  health: { label: "Health", icon: "💊", color: "bg-red-100 text-red-700" },
  personal_care: { label: "Personal care", icon: "💇", color: "bg-rose-100 text-rose-700" },
  education: { label: "Education", icon: "📚", color: "bg-cyan-100 text-cyan-700" },
  kids_family: { label: "Kids & family", icon: "👨‍👩‍👧", color: "bg-rose-100 text-rose-700" },
  pets: { label: "Pets", icon: "🐾", color: "bg-amber-100 text-amber-700" },
  work: { label: "Work", icon: "💼", color: "bg-slate-100 text-slate-700" },
  gifts: { label: "Gifts", icon: "🎁", color: "bg-pink-100 text-pink-700" },
  insurance: { label: "Insurance", icon: "🛡️", color: "bg-slate-100 text-slate-700" },
  emi_loans: { label: "EMI / Loans", icon: "🏦", color: "bg-amber-100 text-amber-700" },
  taxes_fees: { label: "Taxes & fees", icon: "🧾", color: "bg-stone-100 text-stone-700" },
  investment: { label: "Investment", icon: "📈", color: "bg-emerald-100 text-emerald-700" },
  charity: { label: "Charity", icon: "❤️", color: "bg-pink-100 text-pink-700" },
  salary: { label: "Salary", icon: "💰", color: "bg-green-100 text-green-700" },
  freelance: { label: "Freelance", icon: "💼", color: "bg-teal-100 text-teal-700" },
  business: { label: "Business", icon: "🏢", color: "bg-emerald-100 text-emerald-700" },
  bonus: { label: "Bonus", icon: "🎊", color: "bg-green-100 text-green-700" },
  investment_return: { label: "Returns", icon: "📊", color: "bg-lime-100 text-lime-700" },
  interest: { label: "Interest", icon: "💹", color: "bg-lime-100 text-lime-700" },
  rental_income: { label: "Rental income", icon: "🏘️", color: "bg-emerald-100 text-emerald-700" },
  cashback: { label: "Cashback", icon: "💳", color: "bg-cyan-100 text-cyan-700" },
  reimbursement: { label: "Reimbursement", icon: "↪️", color: "bg-teal-100 text-teal-700" },
  gift: { label: "Gift", icon: "🎁", color: "bg-rose-100 text-rose-700" },
  refund: { label: "Refund", icon: "↩️", color: "bg-cyan-100 text-cyan-700" },
  other: { label: "Other", icon: "📌", color: "bg-gray-100 text-gray-700" },
};

export const getCategoryMeta = (category) =>
  CATEGORY_META[category] || CATEGORY_META.other;
